name: codinator

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run_script_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        id: script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SPEC_FILE_PATH: ${{ secrets.SPEC_FILE_PATH }}
        run: |
          stdout=$(python codinator.py | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "result=$stdout" >> "$GITHUB_OUTPUT"

      - name: Create comment
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const output = `${{ steps.script.outputs.result }}`;
            const body = `**Codinator has reviewed this PR!** Please address the below comments and push the changes. Once done, request a review from the assigned reviewer.\n${output}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: body
            });
          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}